version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app/app
      - ./tools.db:/app/tools.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 